version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge